DROP TABLE IF EXISTS TB_COIN;

CREATE TABLE TB_COIN (
  ID NUMBER(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  COIN_NAME VARCHAR(3) NOT NULL,
  COIN_TW_NAME VARCHAR(10) NOT NULL,
  EXCHANGE_RATE NUMBER(14,4) NOT NULL,
  UPDATE_TIME  VARCHAR(20),
  UNIQUE(COIN_NAME)
);
